maps/cenario_dione_kz.txt
maps/cenario_dione_kz.res
gfx/env/BossSKVDSkybk.tga
gfx/env/BossSKVDSkyft.tga
gfx/env/BossSKVDSkylf.tga
gfx/env/BossSKVDSkyrt.tga
gfx/env/BossSKVDSkyup.tga
models/zs_choi_arena_dione/barrel_metal.mdl
models/zs_choi_arena_dione/barrels_pallet.mdl
models/zs_choi_arena_dione/bush_japan_fern_01.mdl
models/zs_choi_arena_dione/fern.mdl
models/zs_choi_arena_dione/pallet_stack.mdl
models/zs_choi_arena_dione/palmtree_green01.mdl
models/zs_choi_arena_dione/palmtree_green02.mdl
models/zs_choi_arena_dione/palmtree01.mdl
models/zs_choi_arena_dione/palmtree02.mdl
models/zs_choi_arena_dione/pred_plant.mdl
models/zs_choi_arena_dione/stone_3_mdl.mdl
models/zs_choi_arena_dione/stone_small.mdl
models/zs_choi_arena_dione/trace_barrel01.mdl
models/zs_choi_arena_dione/bush_fern_small.mdl

