maps/cenario_soy_jackboss.txt
maps/cenario_soy_jackboss.res
sound/zs_choi_arena_jack_skvd/water_sprinkler.wav
models/zs_choi_arena_jack_skvd/bg_big_pipeup04.mdl
models/zs_choi_arena_jack_skvd/chain_01.mdl
models/zs_choi_arena_jack_skvd/chain_02.mdl
models/zs_choi_arena_jack_skvd/cons_yellowpipe_04_1.mdl
models/zs_choi_arena_jack_skvd/cons_yellowpipe_05.mdl
models/zs_choi_arena_jack_skvd/drum_01.mdl
models/zs_choi_arena_jack_skvd/drum_02.mdl
models/zs_choi_arena_jack_skvd/drum_03.mdl
models/zs_choi_arena_jack_skvd/forklift.mdl
models/zs_choi_arena_jack_skvd/pipe_4.mdl
models/zs_choi_arena_jack_skvd/zs_52_control01.mdl
models/zs_choi_arena_jack_skvd/zs_52_light01.mdl
models/zs_choi_arena_jack_skvd/zs_52_pipe01.mdl
models/zs_choi_arena_jack_skvd/zs_52_pipe02.mdl
models/zs_choi_arena_jack_skvd/zs_52_pipe04.mdl
models/zs_choi_arena_jack_skvd/zs_52_pipe05.mdl
models/zs_choi_arena_jack_skvd/zs_52_rubble01.mdl
models/zs_choi_arena_jack_skvd/zs_52_wb01.mdl
models/zs_choi_arena_jack_skvd/zs_52_wb02.mdl