models/cenario_obstacle/as_brokenwall02_big.mdl.mdl
models/cenario_obstacle/bg_antenna.mdl
models/cenario_obstacle/bg_fence_chain.mdl
models/cenario_obstacle/bg_fence_poll.mdl
models/cenario_obstacle/bg_plight.mdl
models/cenario_obstacle/dd_broken.mdl
models/cenario_obstacle/helicopter_blackhawkdown.mdl
models/cenario_obstacle/humv-gun.mdl
models/cenario_obstacle/osprey2.mdl
models/cenario_obstacle/tank_body.mdl
models/cenario_obstacle/tank_cannon.mdl
models/cenario_obstacle/tank_turret.mdl
models/cenario_obstacle/tower.mdl
models/cenario_obstacle/truck_broken01.mdl
sprites/cenario_obstacle/3dmflaora.sp
sprites/cenario_obstacle/flame2.spr
sprites/cenario_obstacle/flame1.spr
maps/cenarioboss_obstacle.txt
maps/cenarioboss_obstacle.res